name: Deploy to AWS and run lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to AWS
        uses: aws-actions/login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create Lambda function payload
        run: |
          zip tips_generator.zip tips_generator.py tips.csv upcoming_tips.html

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code --function-name metaai-dailytips-socials --zip-file fileb://tips_generator.zip

      - name: Invoke Lambda function
        run: |
          aws lambda invoke --function-name metaai-dailytips-socials --payload '{}' output.txt
